export const shopCategories = [
  { value: "art", label: "Art & Craft Supplies" },
  { value: "fashion", label: "Clothing & Fashion" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "food", label: "Food & Beverages" },
  { value: "home", label: "Home & Living" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "technology", label: "Software & Technology Services" },
  { value: "books", label: "Books & Stationery" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "toys", label: "Toys, Kids & Baby Products" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "automotive", label: "Automotive & Tools" },
  { value: "health", label: "Healthcare & Medical Supplies" },
  { value: "furniture", label: "Furniture & Decor" },
  { value: "music", label: "Musical Instruments & Gear" },
  { value: "pet", label: "Pet Supplies" },
  { value: "services", label: "Professional Services" },
  { value: "education", label: "Education & Training" },
  { value: "travel", label: "Travel & Experiences" },
  { value: "other", label: "Other" },
];
